### ISSUE TITLE
Which tool does flowdroid use to generate icc model?

### ISSUE THREAD

**Issue by cincat** [secure-software-engineering/FlowDroid#101]
I use ic3 to generate icc model, in the form of protobuf. But when I try with the DroidBench apks, it cannot result with the same file in iccta_testdata_ic3_result folder. So I just wonder if these file is generated with ic3, or there is another tool can be used as an alternative.

**Comment by cincat** [comment]
@StevenArzt

**Comment by cincat** [comment]
I have made it. The model in FlowDroid is generated by ic3 using parameter -protobuf, however, one should first run Retargeted.jar not Dare before runing ic3. The file Retargeted.jar is in iccta repository.

**Comment by Mprune** [comment]
Hi,I wonder how can i find the Retargeted.jar, i can only find the RetargetedApp.jar and i 've got no idea how to use it.
Thanks a lot!

**Comment by Mprune** [comment]
Hi,when i run RetargetedApp.jar, i get the following error:

Warning: exception while processing dex file 'M:\bs\tools\empty.apk'
Exception: org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00
org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.verifyMagicAndByteOrder(DexBackedDexFile.java:151)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:70)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:84)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:54)
        at soot.DexClassProvider.classesOfDex(DexClassProvider.java:121)
        at soot.SourceLocator.getClassesUnder(SourceLocator.java:206)
        at soot.Scene.loadNecessaryClasses(Scene.java:1351)
        at soot.Main.run(Main.java:214)
        at soot.Main.main(Main.java:152)
        at RetargetedApp.main(RetargetedApp.java:24)
Any ideas Thanks!

**Comment by shanmugasundharamselvadurai** [comment]
Hi, 
Have you guys found the solutions
