### ISSUE TITLE
FLOWDROID ERROR - xception in thread "main" java.lang.NoSuchMethodError: soot.Body.getUnits()Lsoot/PatchingChain;

### ISSUE THREAD

**Issue by jpuentea** [secure-software-engineering/FlowDroid#102]
I'm trying to use FlowDroid for the first time and keep having an error while doing (on windows):

```
java -Xmx4g -cp sootclasses-trunk-jar-with-dependencies.jar;soot-infoflow.jar;soot-infoflow-android.jar;slf4j-api-1.7.5.jar;slf4j-simple-1.7.5.jar;axml-2.0.jar s
oot.jimple.infoflow.android.TestApps.Test "C:\Users\javie\AndroidStudioProjects\Project\malware\73ddc408b518826064878dfc0064c4cd4fe512c0.apk" C:\Users\javie\AppData\Local\Android\Sdk\platforms

```
Running data flow analysis...
Exception in thread "main" java.lang.NoSuchMethodError: soot.Body.getUnits()Lsoot/PatchingChain;
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchHandlerPostBody(LibraryClassPatcher.java:386)
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchHandlerImplementation(LibraryClassPatcher.java:285)
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:44)
        at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1021)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1187)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1160)
        at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Test.java:798)
        at soot.jimple.infoflow.android.TestApps.Test.main(Test.java:249)

**Comment by zhanghan177** [comment]
Are you sure you are running the latest release? Your command looks different from their latest README: https://github.com/secure-software-engineering/FlowDroid#running-the-command-line-tool

**Comment by jpuentea** [comment]
I am following this instructions https://github.com/secure-software-engineering/soot-infoflow-android/wiki

**Comment by zhanghan177** [comment]
I would recommend try this repo's master or develop branch. They are most up-to-date.

**Comment by jpuentea** [comment]
> Your soot is too old. The method signature of the getUnits method looks different now.

which is the soot that will work with this command?

**Comment by MarcMil** [comment]
The current version of the develop branch should work fine.
You can build it yourself or obtain it from https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/

**Comment by jpuentea** [comment]
> The current version of the develop branch should work fine.
> You can build it yourself or obtain it from https://soot-build.cs.uni-paderborn.de/public/origin/develop/soot/soot-develop/build/

Using the same command with the sootclasses-trunk.jar provided in the link outputs the same error. Could it be a error of my java version or the jre? I am using jdk1.8.0_191 and jre1.8.0_191

**Comment by MarcMil** [comment]
Oops, in that case, your FlowDroid is too old, as @zhanghan177 mentioned :)
So the problem is that your FlowDroid build references a method, which does not exist in the current version of soot anymore with that signature.
So I was wrong, it is the other way around; your FlowDroid is too old. You might need to compile your own version of FlowDroid based on the develop branch. This might be the safest option to obtain a working copy.

**Comment by MarcMil** [comment]
If you keep getting the error afterwards, your build version of FlowDroid referenced a different version of soot during build compared to the version you use at runtime.
