### ISSUE TITLE
Error in executing Flowdroid with command line

### ISSUE THREAD

**Issue by RishMeh19** [secure-software-engineering/FlowDroid#106]

**Comment by RishMeh19** [comment]
Sir, I am getting the following error after executing the command-:
java -jar soot-infoflow-cmd-jar-with-dependencies.jar -a com.nice.candy.wallpaper.hd.wallpapers.apk -p /home/rishabh/Documents/Flowdroid/platforms -s SourcesAndSinks

error-:
[main] INFO soot.jimple.infoflow.taintWrappers.EasyTaintWrapper - Loaded wrapper entries for 90 classes and 12 exclusions.
The data flow analysis has failed. Error message: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1927)
at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1289)
at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:237)
at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:196)

is there any error in the main file?

**Comment by RishMeh19** [comment]
I have resolved the previous error as I am not attaching file extension(.txt) to SourcesandSinks file.
Now, after executing the command I am not getting any output in sootOutput folder for various apks I tried on.

**Comment by ferdinan4** [comment]
I had problems too,  I download the release : **soot-infoflow-cmd-jar-with-dependencies.jar
17.9 MB**


I execute the command: 
**java -jar soot-infoflow-cmd-jar-with-dependencies.jar -a ./test.apk -p /home/andro/Android/Sdk/platforms/  -s ./SourcesAndSinks.txt** 
[main] INFO soot.jimple.infoflow.taintWrappers.EasyTaintWrapper - Loaded wrapper entries for 90 classes and 12 exclusions.
[main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Loading dex files...
[main] INFO soot.jimple.infoflow.android.SetupApplication - ARSC file parsing took 0.024381284 seconds
[main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Collecting callbacks in DEFAULT mode...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Callback analysis done.
[main] WARN soot.jimple.infoflow.android.resources.LayoutFileParser - Could not find layout class x
[main] WARN soot.jimple.infoflow.android.resources.LayoutFileParser - Could not find layout class android.support.constraint.ConstraintLayout
[main] WARN soot.jimple.infoflow.android.resources.LayoutFileParser - Could not find layout class android.support.constraint.ConstraintLayout
[main] WARN soot.jimple.infoflow.android.resources.LayoutFileParser - Could not find layout class android.support.constraint.ConstraintLayout
[main] WARN soot.jimple.infoflow.android.resources.LayoutFileParser - Could not find layout class x
[main] WARN soot.jimple.infoflow.android.resources.LayoutFileParser - Could not find layout class x
[main] WARN soot.jimple.infoflow.android.resources.LayoutFileParser - Could not find layout class android.support.constraint.ConstraintLayout
[main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 1 components...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Callback analysis terminated normally
[main] INFO soot.jimple.infoflow.android.SetupApplication - Entry point calculation done.
[main] INFO soot.jimple.infoflow.android.source.AccessPathBasedSourceSinkManager - Created a SourceSinkManager with 39 sources, 126 sinks, and 1 callback methods.
[main] INFO soot.jimple.infoflow.android.SetupApplication - Running data flow analysis on ./marinao.apk with 39 sources and 126 sinks...
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Implicit flow tracking is NOT enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Exceptional flow tracking is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Running with a maximum access path length of 5
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using path-agnostic result collection
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Recursive access path shortening is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Taint analysis enabled: true
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using alias algorithm FlowSensitive
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Callgraph construction took 0.002917244 seconds
[main] INFO soot.jimple.infoflow.codeOptimization.InterproceduralConstantValuePropagator - Removing side-effect free methods is disabled
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Dead code elimination took 0.349185805 seconds
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Callgraph has 743 edges
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Starting Taint Analysis
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Using context- and flow-sensitive solver
[main] WARN soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Running with limited join point abstractions can break context-sensitive path builders
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Looking for sources and sinks...
[main] ERROR soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - No sources found, aborting analysis
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
[main] WARN soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - No results found.
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Data flow solver took 0.498267 seconds. Maximum memory consumption: 56.368224 MB
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 0 leaks


I dont get any report..

Any Idea THANKS!

**Comment by StevenArzt** [comment]
@RishMeh19 The ```SootOutput``` folder is creted by Soot. FlowDroid does not store any data there. The results of the data flow analysis are printed to the command line. Alternatively, you can use the  ```-o``` command line option to write the results into an XML file. If you want to integrate FlowDroid into your own project, you can also use the ```InfoflowResults``` object to access the results through an API, instead of having to parse files.

@ferdinan4  Your data flow analysis did not yield any results. Maybe there are no flows inside your app that correspond to your source/sink definitions. Please re-check your sources and sinks. In fact, there is a report, but it's empty: ```[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 0 leaks```
