### ISSUE TITLE
Wrong IccLink error using IccTA

### ISSUE THREAD

**Issue by zjbthomas** [secure-software-engineering/FlowDroid#117]
Hi, I got Wrong IccLink error when using FlowDroid 2.7.1 (the latest release) with IccTA. I somehow think it is a bug of IccTA in FlowDroid but I am not sure yet.

Here is an example app with such error. I also enclosed the ICC model generated by IC3 0.2.0.
[APKandICCModel.zip](https://github.com/secure-software-engineering/FlowDroid/files/2801267/APKandICCModel.zip)

Here is how I try to debug it. FlowDroid will call `constructCallgraphInternal()` for multiple times in method `calculateCallbackMethods()` of class `SetupApplication`. Every time, IccTA will create redirections. The following Wrong IccLink error happens at the seond round of instrumentation.

> [main] ERROR soot.jimple.infoflow.android.SetupApplication - Could not calculate callback methods
java.lang.RuntimeException: Wrong IccLink [<com.tomer.alwayson.services.StarterService: void onCreate()> [$z0 = $r5.<com.tomer.alwayson.helpers.Prefs: boolean notificationsAlerts>] com.tomer.alwayson.services.NotificationListener]
	at soot.jimple.infoflow.android.iccta.IccRedirectionCreator.getRedirectMethod(IccRedirectionCreator.java:161)
	at soot.jimple.infoflow.android.iccta.IccRedirectionCreator.redirectToDestination(IccRedirectionCreator.java:96)
	at soot.jimple.infoflow.android.iccta.IccInstrumenter.onBeforeCallgraphConstruction(IccInstrumenter.java:74)
	at soot.jimple.infoflow.android.SetupApplication.constructCallgraphInternal(SetupApplication.java:547)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(SetupApplication.java:682)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:476)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:446)
	at soot.jimple.infoflow.android.SetupApplication.processEntryPoint(SetupApplication.java:1393)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1359)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1306)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:333)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:231)

In ICC model, there is an intent like this:
> components {
  name: "com.tomer.alwayson.services.StarterService"
 ...
  exit_points {
    instruction {
      statement: "virtualinvoke r0.<com.tomer.alwayson.services.StarterService: android.content.ComponentName startService(android.content.Intent)>(r1)"
      class_name: "com.tomer.alwayson.services.StarterService"
      method: "<com.tomer.alwayson.services.StarterService: void onCreate()>"
      id: 31
    }

So IccTA will find the 31st statement in method `com.tomer.alwayson.services.StarterService: void onCreate()`. In the first round of IccTA instrumentation, it works fine and find the correct invoke statement. However, in the second round, since redirector methods are added to the body of this method, the 31st statement is not the same and correct one. The incorrect statement is an assign statement, which leads to Wrong IccLink error.

**Comment by ShengliangD** [comment]
I also meet with this problem. Any idea how to solve it?

**Comment by tanjina12** [comment]
Whenever I try to  construct the call graph including ICC model, I'm also getting this Exception for some apps!
