### ISSUE TITLE
NullPointerException during analysis

### ISSUE THREAD

**Issue by turban1988** [secure-software-engineering/FlowDroid#148]
When I try to analyze the newest [WhatsApp APK](https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/whatsapp-2-19-109-release/whatsapp-messenger-2-19-109-android-apk-download/) the analysis crashes with a `NullPointerExcpetion ` during the flow analyis. I tried all aliasing  algorithms but all failed. 

```
[main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 18 components...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Callback analysis terminated normally
[main] INFO soot.jimple.infoflow.android.SetupApplication - Entry point calculation done.
[main] INFO soot.jimple.infoflow.android.source.AccessPathBasedSourceSinkManager - Created a SourceSinkManager with 39 sources, 126 sinks, and 35 callback methods.
[main] INFO soot.jimple.infoflow.android.SetupApplication - Collecting callbacks and building a callgraph took 64 seconds
[main] INFO soot.jimple.infoflow.android.SetupApplication - Running data flow analysis on <path>\whatsapp.apk with 39 sources and 126 sinks...
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Implicit flow tracking is NOT enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Exceptional flow tracking is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Running with a maximum access path length of 5
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using path-agnostic result collection
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Recursive access path shortening is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Taint analysis enabled: true
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using alias algorithm PtsBased
[main] ERROR soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Exception during data flow analysis
java.lang.NullPointerException
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.generateMessageObtainMethod(LibraryClassPatcher.java:228)
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchMessageObtainImplementation(LibraryClassPatcher.java:136)
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:75)
        at soot.jimple.infoflow.AbstractInfoflow.constructCallgraph(AbstractInfoflow.java:352)
        at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:271)
        at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:239)
        at soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow.runAnalysis(SetupApplication.java:1180)
        at soot.jimple.infoflow.android.SetupApplication.processEntryPoint(SetupApplication.java:1424)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1359)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1306)
        at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:333)
        at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:231)
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 0 leaks
```

**Comment by StevenArzt** [comment]
The issue should be fixed. Please report back in case there is still a problem.
