### ISSUE TITLE
IllegalArgumentException in Trove on TObjectHashingStrategy not implementing equals and hashCode in a concise way

### ISSUE THREAD

**Issue by SvenPeldszus** [secure-software-engineering/FlowDroid#229]
We used flow-droid to analyze some Java projects and got the IllegalArgument exception, mentioned in the title. Afterward, we tried to build FlowDroid our own, using Maven, and noticed that the same exception appears in the test cases. 

The trace from the FlowDroid tests:

```[WARNING] Tests run: 11, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 45.541 s - in soot.jimple.infoflow.test.junit.MapTests
[INFO] Running soot.jimple.infoflow.test.junit.ImplicitFlowTests
Starting convertTest...
convertTest took 1.580074404 seconds
Starting stringClassTest...
stringClassTest took 2.852977518 seconds
Exception in thread "FlowDroid" java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class soot.jimple.infoflow.data.Abstraction id= 26288056 hashCode= 2064667572 toString= _<java.lang.System: java.io.Console cons> * <+length> | $stack2 = staticinvoke <java.lang.String: java.lang.String valueOf(java.lang.Object)>(l1)>>; object #2 =class soot.jimple.infoflow.data.Abstraction id= 1175264684 hashCode= 2064667572 toString= _<java.lang.System: java.io.Console cons> * <+length> | $stack2 = staticinvoke <java.lang.String: java.lang.String valueOf(java.lang.Object)>(l1)>>

hashCode() and/or equals() have inconsistent implementation
Key set lost entries, now got 1 instead of 12. This can manifest itself as an apparent duplicate key.
	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
	at gnu.trove.set.hash.TCustomHashSet.rehash(TCustomHashSet.java:178)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
	at gnu.trove.set.hash.TCustomHashSet.add(TCustomHashSet.java:120)
	at soot.jimple.infoflow.data.Abstraction.addNeighbor(Abstraction.java:549)
	at soot.jimple.infoflow.data.Abstraction.addNeighbor(Abstraction.java:36)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.propagate(IFDSSolver.java:633)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$1.accept(IFDSSolver.java:311)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$1.accept(IFDSSolver.java:287)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:287)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:65)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:733)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The error trace from our application:

```[main] INFO soot.jimple.infoflow.Infoflow - Resetting Soot...
[main] INFO soot.jimple.infoflow.Infoflow - Basic class loading done.
[main] WARN soot.jimple.infoflow.entryPointCreators.DefaultEntryPointCreator - Cannot create valid constructor for org.eclipse.equinox.security.storage.provider.IPreferencesContainer, because it is an interface and cannot substitute with subclass
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Implicit flow tracking is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Exceptional flow tracking is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Running with a maximum access path length of 5
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using path-agnostic result collection
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Recursive access path shortening is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Taint analysis enabled: true
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using alias algorithm FlowSensitive
[main] INFO soot.jimple.infoflow.Infoflow - Callgraph construction took 14 seconds
[main] INFO soot.jimple.infoflow.codeOptimization.InterproceduralConstantValuePropagator - Removing side-effect free methods is disabled
[main] INFO soot.jimple.infoflow.Infoflow - Dead code elimination took 1.459031394 seconds
[main] INFO soot.jimple.infoflow.Infoflow - Callgraph has 14746 edges
[main] INFO soot.jimple.infoflow.Infoflow - Starting Taint Analysis
[main] INFO soot.jimple.infoflow.data.FlowDroidMemoryManager - Initializing FlowDroid memory manager...
[main] INFO soot.jimple.infoflow.Infoflow - Using context- and flow-sensitive solver
[main] WARN soot.jimple.infoflow.Infoflow - Running with limited join point abstractions can break context-sensitive path builders
[main] INFO soot.jimple.infoflow.Infoflow - Looking for sources and sinks...
[main] INFO soot.jimple.infoflow.Infoflow - Source lookup done, found 4 sources and 1 sinks.
[FlowDroid] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class soot.jimple.infoflow.data.Abstraction id= 52250240 hashCode= -335382301 toString= _<java.lang.Throwable: java.lang.StackTraceElement[] UNASSIGNED_STACK> * <+length> | specialinvoke $stack17.<java.lang.StringIndexOutOfBoundsException: void <init>(int)>(l2)>>; object #2 =class soot.jimple.infoflow.data.Abstraction id= 2033127764 hashCode= -335382301 toString= _<java.lang.Throwable: java.lang.StackTraceElement[] UNASSIGNED_STACK> * <+length> | specialinvoke $stack17.<java.lang.StringIndexOutOfBoundsException: void <init>(int)>(l2)>>

hashCode() and/or equals() have inconsistent implementation
Key set lost entries, now got 1 instead of 12. This can manifest itself as an apparent duplicate key.
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class soot.jimple.infoflow.data.Abstraction id= 52250240 hashCode= -335382301 toString= _<java.lang.Throwable: java.lang.StackTraceElement[] UNASSIGNED_STACK> * <+length> | specialinvoke $stack17.<java.lang.StringIndexOutOfBoundsException: void <init>(int)>(l2)>>; object #2 =class soot.jimple.infoflow.data.Abstraction id= 2033127764 hashCode= -335382301 toString= _<java.lang.Throwable: java.lang.StackTraceElement[] UNASSIGNED_STACK> * <+length> | specialinvoke $stack17.<java.lang.StringIndexOutOfBoundsException: void <init>(int)>(l2)>>

hashCode() and/or equals() have inconsistent implementation
Key set lost entries, now got 1 instead of 12. This can manifest itself as an apparent duplicate key.
	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
	at gnu.trove.set.hash.TCustomHashSet.rehash(TCustomHashSet.java:178)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
	at gnu.trove.set.hash.TCustomHashSet.add(TCustomHashSet.java:120)
	at soot.jimple.infoflow.data.Abstraction.addNeighbor(Abstraction.java:549)
	at soot.jimple.infoflow.data.Abstraction.addNeighbor(Abstraction.java:36)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.propagate(IFDSSolver.java:633)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processExit(IFDSSolver.java:489)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.processExit(InfoflowSolver.java:127)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:738)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
[main] ERROR soot.jimple.infoflow.Infoflow - Exception during data flow analysis
java.lang.RuntimeException: There were exceptions during IFDS analysis. Exiting.
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:248)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:215)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:187)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:483)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:185)
	at soot.jimple.infoflow.AbstractInfoflow.computeInfoflow(AbstractInfoflow.java:135)
	at org.gravity.flowdroid.Example.testSecureStorage(Example.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:171)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:593)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:205)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class soot.jimple.infoflow.data.Abstraction id= 52250240 hashCode= -335382301 toString= _<java.lang.Throwable: java.lang.StackTraceElement[] UNASSIGNED_STACK> * <+length> | specialinvoke $stack17.<java.lang.StringIndexOutOfBoundsException: void <init>(int)>(l2)>>; object #2 =class soot.jimple.infoflow.data.Abstraction id= 2033127764 hashCode= -335382301 toString= _<java.lang.Throwable: java.lang.StackTraceElement[] UNASSIGNED_STACK> * <+length> | specialinvoke $stack17.<java.lang.StringIndexOutOfBoundsException: void <init>(int)>(l2)>>

hashCode() and/or equals() have inconsistent implementation
Key set lost entries, now got 1 instead of 12. This can manifest itself as an apparent duplicate key.
	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
	at gnu.trove.set.hash.TCustomHashSet.rehash(TCustomHashSet.java:178)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
	at gnu.trove.set.hash.TCustomHashSet.add(TCustomHashSet.java:120)
	at soot.jimple.infoflow.data.Abstraction.addNeighbor(Abstraction.java:549)
	at soot.jimple.infoflow.data.Abstraction.addNeighbor(Abstraction.java:36)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.propagate(IFDSSolver.java:633)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processExit(IFDSSolver.java:489)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.processExit(InfoflowSolver.java:127)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:738)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by SvenPeldszus** [comment]
If you need any more information I'll be glad to provide them.

**Comment by MarcMil** [comment]
This bug should be fixed by now. The problem was that certain elements in the set were reused, which changed their hashcode. This is no longer the case.
