### ISSUE TITLE
FlowDroid crashes with some apps 

### ISSUE THREAD

**Issue by salmanee** [secure-software-engineering/FlowDroid#241]
FlowDroid seems to be working well. However, I when I tried running it against a specific set of apps it crashes with the following error message:

> The data flow analysis has failed. Error message: None of the basic classes could be loaded! Check your Soot class path!
java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
	at soot.Scene.loadBasicClasses(Scene.java:1675)
	at soot.Scene.loadNecessaryClasses(Scene.java:1760)
	at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1129)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1377)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1352)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:341)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:239)

Is there any reason why this could be happening?

**Comment by StevenArzt** [comment]
Can you provide a download link for these apps?

**Comment by salmanee** [comment]
Thank you for your response @StevenArzt .. Did the previous link in my post (https://drive.google.com/open?id=1o2-qx2uB1z15JPCR8GpslLx-rOGEPAAg) not work for you?
