### ISSUE TITLE
java.lang.RuntimeException: no superclass for java.lang.Thread when generating call graph

### ISSUE THREAD

**Issue by X-czh** [secure-software-engineering/FlowDroid#268]
When I used FlowDroid 2.7.1 with openjdk-8 on Ubuntu 20.04 machine, I got the following error when FlowDroid is generating the call graph (with the default infoflow configuration using SPARK):

```
java.lang.RuntimeException: no superclass for java.lang.Thread
	at soot.SootClass.getSuperclass(SootClass.java:877)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.buildAncestryTree(BytecodeHierarchy.java:76)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas_(BytecodeHierarchy.java:170)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas_(BytecodeHierarchy.java:121)
	at soot.jimple.toolkits.typing.fast.BytecodeHierarchy.lcas(BytecodeHierarchy.java:288)
	at soot.jimple.toolkits.typing.fast.TypeResolver.applyAssignmentConstraints(TypeResolver.java:511)
	at soot.jimple.toolkits.typing.fast.TypeResolver.inferTypes(TypeResolver.java:144)
	at soot.jimple.toolkits.typing.TypeAssigner.internalTransform(TypeAssigner.java:121)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:73)
	at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:105)
	at soot.Pack.apply(Pack.java:125)
        .........
```

The same error occured when I explicitly configured FlowDroid to use the CHA algorithm as well. I had no idea what went wrong, could anyone help?

**Comment by X-czh** [comment]
I just figured out the problem: I forgot to include rt.jar in the path.
