### ISSUE TITLE
Get NoSuchMethod error when generate ICFG with flowdroid as a library

### ISSUE THREAD

**Issue by YaphetsH** [secure-software-engineering/FlowDroid#296]
Hello,I wanna to use FlowDroid as the library with analyzing app about inter-procedure.So I use these jar library to develop:
-soot-trunk.jar
-soot-infoflow.jar
-soot-infoflow-android.jar

And after integrating them ,I use some code as below to run app,But I get NoSuchMethod Error about SootMethodRef:

here is the code(eg. scala):
`   val config = new InfoflowAndroidConfiguration
    config.getAnalysisFileConfig.setAndroidPlatformDir(platformPath);
    config.getAnalysisFileConfig.setTargetAPKFile(apkPath);
    Options.v.set_whole_program(true)
    Options.v.set_allow_phantom_refs(true)
    Options.v.set_prepend_classpath(true)
    Options.v.set_process_multiple_dex(true)
    Options.v.set_src_prec(Options.src_prec_apk)
    Options.v.set_android_jars(platformPath)
    Options.v.force_overwrite
    Options.v.set_process_dir(Collections.singletonList(apkPath))
    Options.v.set_output_format(Options.output_format_dex)
    Options.v.setPhaseOption("cg.spark", "on")
    Options.v.set_no_bodies_for_excluded(true)
    Scene.v.addBasicClass("java.io.PrintStream", SootClass.SIGNATURES)
    Scene.v.loadNecessaryClasses()
    config.setSootIntegrationMode(InfoflowAndroidConfiguration.SootIntegrationMode.UseExistingInstance);
    val sootConfig = new SootConfigForAndroid
    sootConfig.setSootOptions(soot.options.Options.v, config)
    val app  = new SetupApplication(config)
    app.setCallbackFile(AndroidCallBackFile)
    app.setSootConfig(sootConfig)
    app.constructCallgraph()`

and here is the err-stacktrace:
`[main] INFO soot.jimple.infoflow.android.SetupApplication - ARSC file parsing took 0.0412124 seconds
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Registered a memory warning system for 4,909.5 MiB
[main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 7 components...
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
Exception in thread "main" java.lang.NoSuchMethodError: soot.SootMethodRef.isConstructor()Z
	at soot.jimple.infoflow.android.entryPointCreators.components.AbstractComponentEntryPointCreator.instrumentDummyMainMethod(AbstractComponentEntryPointCreator.java:234)
	at soot.jimple.infoflow.android.entryPointCreators.components.AbstractComponentEntryPointCreator.createDummyMainInternal(AbstractComponentEntryPointCreator.java:210)
	at soot.jimple.infoflow.entryPointCreators.BaseEntryPointCreator.createDummyMain(BaseEntryPointCreator.java:153)
	at soot.jimple.infoflow.android.entryPointCreators.AbstractAndroidEntryPointCreator.createDummyMain(AbstractAndroidEntryPointCreator.java:32)
	at soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator.createDummyMainInternal(AndroidEntryPointCreator.java:283)
	at soot.jimple.infoflow.entryPointCreators.BaseEntryPointCreator.createDummyMain(BaseEntryPointCreator.java:153)
	at soot.jimple.infoflow.android.entryPointCreators.AbstractAndroidEntryPointCreator.createDummyMain(AbstractAndroidEntryPointCreator.java:32)
	at soot.jimple.infoflow.android.SetupApplication.createMainMethod(SetupApplication.java:1109)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(SetupApplication.java:708)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:517)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:464)
	at soot.jimple.infoflow.android.SetupApplication.processEntryPoint(SetupApplication.java:1509)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1475)
	at soot.jimple.infoflow.android.SetupApplication.constructCallgraph(SetupApplication.java:1319)`

can anyone help me to solve this problem? Thanks~

**Comment by YaphetsH** [comment]
Finally,the soot version  doesn't match flowdroid v2.8 use.So Change and downgrade the soot version to 4.21 can help solve this problem. 
Done~
