### ISSUE TITLE
Thread execution failure

### ISSUE THREAD

**Issue by xinjin95** [secure-software-engineering/FlowDroid#369]
Hi FlowDroid team,

I'd like to report a crash issue while using the latest FlowDroid cmd executable (version 2.9.0) `soot-infoflow-cmd-2.9.0-jar-with-dependencies.jar`. I got following crash logs for testing several apps:

```bash
[FlowDroid] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: java.lang.RuntimeException: interface needed!
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: interface needed!
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getFlowSummariesForMethod(SummaryTaintWrapper.java:1182)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.computeTaintsForMethod(SummaryTaintWrapper.java:839)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getTaintsForMethod(SummaryTaintWrapper.java:755)
	at soot.jimple.infoflow.problems.rules.WrapperPropagationRule.computeWrapperTaints(WrapperPropagationRule.java:93)
	at soot.jimple.infoflow.problems.rules.WrapperPropagationRule.propagateCallToReturnFlow(WrapperPropagationRule.java:147)
	at soot.jimple.infoflow.problems.rules.PropagationRuleManager.applyCallToReturnFlowFunction(PropagationRuleManager.java:190)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargetsInternal(InfoflowProblem.java:780)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargets(InfoflowProblem.java:757)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:98)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:41)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:333)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:64)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:751)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: interface needed!
	at soot.Hierarchy.getSuperinterfacesOfIncluding(Hierarchy.java:339)
	at soot.Hierarchy.getSuperinterfacesOf(Hierarchy.java:369)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getAllParentClasses(SummaryTaintWrapper.java:1305)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.access$000(SummaryTaintWrapper.java:71)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.checkInterfaces(SummaryTaintWrapper.java:231)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.getSummaries(SummaryTaintWrapper.java:135)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.load(SummaryTaintWrapper.java:100)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.load(SummaryTaintWrapper.java:89)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 20 more
Exception in thread "FlowDroid" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: interface needed!
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getFlowSummariesForMethod(SummaryTaintWrapper.java:1182)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.computeTaintsForMethod(SummaryTaintWrapper.java:839)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getTaintsForMethod(SummaryTaintWrapper.java:755)
	at soot.jimple.infoflow.problems.rules.WrapperPropagationRule.computeWrapperTaints(WrapperPropagationRule.java:93)
	at soot.jimple.infoflow.problems.rules.WrapperPropagationRule.propagateCallToReturnFlow(WrapperPropagationRule.java:147)
	at soot.jimple.infoflow.problems.rules.PropagationRuleManager.applyCallToReturnFlowFunction(PropagationRuleManager.java:190)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargetsInternal(InfoflowProblem.java:780)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargets(InfoflowProblem.java:757)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:98)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:41)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:333)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:64)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:751)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: interface needed!
	at soot.Hierarchy.getSuperinterfacesOfIncluding(Hierarchy.java:339)
	at soot.Hierarchy.getSuperinterfacesOf(Hierarchy.java:369)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getAllParentClasses(SummaryTaintWrapper.java:1305)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.access$000(SummaryTaintWrapper.java:71)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.checkInterfaces(SummaryTaintWrapper.java:231)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.getSummaries(SummaryTaintWrapper.java:135)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.load(SummaryTaintWrapper.java:100)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.load(SummaryTaintWrapper.java:89)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 20 more
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
[main] ERROR soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Exception during data flow analysis
java.lang.RuntimeException: There were exceptions during IFDS analysis. Exiting.
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:247)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:214)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:186)
	at soot.jimple.infoflow.Infoflow.runTaintAnalysis(Infoflow.java:523)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:312)
	at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:248)
	at soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow.runAnalysis(SetupApplication.java:1299)
	at soot.jimple.infoflow.android.SetupApplication.processEntryPoint(SetupApplication.java:1549)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1484)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1431)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:351)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:245)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: interface needed!
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getFlowSummariesForMethod(SummaryTaintWrapper.java:1182)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.computeTaintsForMethod(SummaryTaintWrapper.java:839)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getTaintsForMethod(SummaryTaintWrapper.java:755)
	at soot.jimple.infoflow.problems.rules.WrapperPropagationRule.computeWrapperTaints(WrapperPropagationRule.java:93)
	at soot.jimple.infoflow.problems.rules.WrapperPropagationRule.propagateCallToReturnFlow(WrapperPropagationRule.java:147)
	at soot.jimple.infoflow.problems.rules.PropagationRuleManager.applyCallToReturnFlowFunction(PropagationRuleManager.java:190)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargetsInternal(InfoflowProblem.java:780)
	at soot.jimple.infoflow.problems.InfoflowProblem$1$4.computeTargets(InfoflowProblem.java:757)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:98)
	at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeCallToReturnFlowFunction(InfoflowSolver.java:41)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processCall(IFDSSolver.java:333)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:64)
	at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:751)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: interface needed!
	at soot.Hierarchy.getSuperinterfacesOfIncluding(Hierarchy.java:339)
	at soot.Hierarchy.getSuperinterfacesOf(Hierarchy.java:369)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.getAllParentClasses(SummaryTaintWrapper.java:1305)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper.access$000(SummaryTaintWrapper.java:71)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.checkInterfaces(SummaryTaintWrapper.java:231)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.getSummaries(SummaryTaintWrapper.java:135)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.load(SummaryTaintWrapper.java:100)
	at soot.jimple.infoflow.methodSummary.taintWrappers.SummaryTaintWrapper$1.load(SummaryTaintWrapper.java:89)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 20 more
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 0 leaks
```

It occurs for several apps and there's not such crash errors when I switched to version 2.8.0.

**Comment by StevenArzt** [comment]
Have you tried the latest development version? The current code seems fine. Please try to build the current "develop" branch on the command line: ``mvn install -DskipTests`` should work.

**Comment by valbrux** [comment]
Same issue here, also when building the latest "develop" version.

**Comment by MarcMil** [comment]
The soot error message is pretty useless. It should specify which class is expected to be an interface; we should change this in soot.

Probably the same bug as https://github.com/secure-software-engineering/FlowDroid/issues/340

We should refrain of setting the modifiers of classes which are not phantom at least (if we could load them they should have the proper modifiers) and maybe have some sort of validator to run optionally during the build of FlowDroid to verify that the data in the summary files are conform to the actual JRE classes.

**Comment by StevenArzt** [comment]
The bug should be gone now. There was a very stupid bug in the summary parser. Please test again.

**Comment by valbrux** [comment]
Retested and solved from my side, thanks

**Comment by SBz19** [comment]
Apologies for borrowing this thread as I am also experiencing this issue. Based on the description of the tool i have followed and used the 2.9 version dependencies jar file as i am intending to just execute its command line interface. However it is still not working on my end. May I know specifically which release should i be using in order to run the tool's command line interface?
