### ISSUE TITLE
Issue with CLI : Error when looking for manifest

### ISSUE THREAD

**Issue by khemrajrathore** [secure-software-engineering/FlowDroid#446]
@StevenArzt  Getting this error when running 
`java -jar soot-infoflow-cmd-2.9.0-jar-with-dependencies.jar -a testdroid-sample-app.apk -p /usr/lib/android-sdk/platforms -s SourcesAndSinks.txt`

[main] INFO soot.jimple.infoflow.cmd.MainClass - Analyzing app /home/ubuntu/logtesting/testdroid-sample-app.apk (1 of 1)...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
The data flow analysis has failed. Error message: Error when looking for manifest in apk: java.util.zip.ZipException: zip END header not found
java.lang.RuntimeException: Error when looking for manifest in apk: java.util.zip.ZipException: zip END header not found
	at soot.Scene.getTargetSDKVersion(Scene.java:534)
	at soot.Scene.getAndroidAPIVersion(Scene.java:448)
	at soot.Scene.getAndroidJarPath(Scene.java:407)
	at soot.jimple.infoflow.android.SetupApplication.getClasspath(SetupApplication.java:1148)
	at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1196)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1456)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1431)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:351)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:245)

**Comment by StevenArzt** [comment]
Can you provide the APK?

**Comment by khemrajrathore** [comment]
https://github.com/bitbar/testdroid-samples/blob/master/apps/builds/BitbarSampleApp.apk
