### ISSUE TITLE
Question about adding multi lib when using soot-inflow-summary

### ISSUE THREAD

**Issue by LeoYelton** [secure-software-engineering/FlowDroid#449]
`soot.jimple.infoflow.methodSummary.Main  `  when I add multi 'toAnalyse' class,such as 
```
'Android\\Sdk\\platforms\\android-23\\android.jar";
Sdk\\platforms\\android-23\\data\\layoutlib.jar;" +
Sdk\\platforms\\android-23\\optional\\org.apache.http.legacy.jar;"
Sdk\\platforms\\android-23\\uiautomator.jar";'. 
```
It cause the exception of arraylist unexpected mod count which is a multithread safe exception.  I use the absoulute path , not relative path.Above is just an example.

**Comment by StevenArzt** [comment]
Please provide your full command line. Have you tried to analyze the libraries one after the other instead of all at the same time?

**Comment by LeoYelton** [comment]
I've tried to analyse lib in turn and it'll not have mistake when analyse only one library. The lib i use are the jars under the any android sdk lib folder. Here are the commands siplified below:
```
-lf -sf C:\Users\secidea\AppData\Local\Android\Sdk\platforms\android-23\data\layoutlib.jar;C:\Users\secidea\AppData\Local\Android\Sdk\platforms\android-23\android.jar 
C:\Users\Desktop\flowdroidoutput
```
It 'll cause 
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator$AnalysisTasksComparator.getDependencyCount(SummaryGenerator.java:199)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator$AnalysisTasksComparator.compare(SummaryGenerator.java:184)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator$AnalysisTasksComparator.compare(SummaryGenerator.java:177)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:239)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1464)
```

**Comment by LeoYelton** [comment]
[android-21.zip](https://github.com/secure-software-engineering/FlowDroid/files/8320757/android-21.zip)
Here are the lib I mentioned above.

**Comment by StevenArzt** [comment]
Hopefully, my code change fixes the issue. Compile FlowDroid from the "develop" branch and try again.

**Comment by LeoYelton** [comment]
Thank you , professor . When I run two jars it already fix. When I try to run a aggragte of jars from my maven repository. It cause a fatal error and a long time without outputing. You can try in your maven repo for testing. I added the aggregate code downside.
```
private String getAllClassPathOrJarToAnalyze(ArrayList<String> classPathAndJars,String rootPath){
        List<String> filesToAnalyze = Arrays.asList(rootPath.split(File.pathSeparator));
        for (String fileStr : filesToAnalyze) {
            File file = new File(fileStr);
            if (!file.exists()) {
                System.err.println("File not found: " + file);
                System.exit(1);
                return "";
            }
            if (file.isDirectory()) {
                Collection<File> files = FileUtils.listFiles(file, new String[]{"jar"}, true);
                ArrayList<File> filesAsList = new ArrayList<>(files);
                for (int c = 0; c < filesAsList.size(); c++) {
                    File f = filesAsList.get(c);
                    classPathAndJars.add(f.getPath());
                }
            }
        }
        if(classPathAndJars.size()==0&&rootPath.length()>0){
            return rootPath;
        }
        return classPathAndJars.stream().collect(Collectors.joining(";"));
    }
```
And the exception cause is as follows:
```
java.lang.RuntimeException: Failed to convert <org.springframework.http.server.reactive.JettyHeadersAdapter$HeaderEntry: java.util.List getValue()>

	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2250)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:446)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator$AnalysisTasksComparator.getDependencyCount(SummaryGenerator.java:203)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator$AnalysisTasksComparator.compare(SummaryGenerator.java:184)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator$AnalysisTasksComparator.compare(SummaryGenerator.java:177)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1464)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator.createMethodSummaries(SummaryGenerator.java:337)
	at soot.jimple.infoflow.methodSummary.Main.createSummaries(Main.java:421)
	at soot.jimple.infoflow.methodSummary.Main.runGenerateSummaryWithSpecificClassRoot(Main.java:341)
	at soot.jimple.infoflow.methodSummary.Main.errorGenerateSummary(Main.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: Trying to create virtual invoke expression for interface type (org.eclipse.jetty.http.HttpFields in file null). Use JInterfaceInvokeExpr instead!
	at soot.jimple.internal.JVirtualInvokeExpr.<init>(JVirtualInvokeExpr.java:51)
	at soot.jimple.Jimple.newVirtualInvokeExpr(Jimple.java:469)
	at soot.asm.AsmMethodSource.convertMethodInsn(AsmMethodSource.java:1434)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1966)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2248)
	... 79 more

Disconnected from the target VM, address: 'javadebug', transport: 'shared memory'

Process finished with exit code -1

```
And I try in turn in a loop of analyzing spring jars this time yet. It doesn't happen this cause.

**Comment by StevenArzt** [comment]
You seem to have inconsistent classes on your target path, probably a result of your merge. The class ``org.eclipse.jetty.http.HttpFields`` should normally be a class according to [its JavaDoc](https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/http/HttpField.html). The invocation that Soot processes also refers to a class. For some reason, however, ``org.eclipse.jetty.http.HttpFields`` is an interface on your target path and not a class. That leads to the error. You should check whether your have incompatible JARs.

**Comment by LeoYelton** [comment]
Another question of running those jars in turn instead of giving multiple jars, I get the wrong result minutes before.
```
method: <javax.swing.JComponent: java.awt.Insets getInsets()>
source: Gap <javax.swing.border.Border: java.awt.Insets getBorderInsets(java.awt.Component)> Parameter 0
sink  : Field true
alias : true
------------------------------------
Method <javax.swing.JComponent: java.awt.Insets getInsets()> done.
Method <java.awt.Container: void addPropertyChangeListener(java.beans.PropertyChangeListener)> done.
Method <javax.swing.JComponent: void setDoubleBuffered(boolean)> done.

com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: Java heap space

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at soot.SourceLocator.lookupInArchive(SourceLocator.java:639)
	at soot.SourceLocator.lookupInClassPath(SourceLocator.java:617)
	at soot.JavaClassProvider.find(JavaClassProvider.java:60)
	at soot.SourceLocator.getClassSource(SourceLocator.java:187)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:250)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:240)
	at soot.SootResolver.bringToSignatures(SootResolver.java:310)
	at soot.SootResolver.bringToBodies(SootResolver.java:350)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:187)
	at soot.SootResolver.resolveClass(SootResolver.java:152)
	at soot.Scene.tryLoadClass(Scene.java:980)
	at soot.Scene.loadBasicClasses(Scene.java:1713)
	at soot.Scene.loadNecessaryClasses(Scene.java:1804)
	at soot.jimple.infoflow.AbstractInfoflow.initializeSoot(AbstractInfoflow.java:276)
	at soot.jimple.infoflow.methodSummary.generator.SummaryInfoflow.initializeSoot(SummaryInfoflow.java:50)
	at soot.jimple.infoflow.AbstractInfoflow.initializeSoot(AbstractInfoflow.java:173)
	at soot.jimple.infoflow.methodSummary.generator.SummaryInfoflow.initializeSoot(SummaryInfoflow.java:44)
	at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:185)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator.createMethodSummary(SummaryGenerator.java:679)
	at soot.jimple.infoflow.methodSummary.generator.SummaryGenerator.createMethodSummaries(SummaryGenerator.java:407)
	at soot.jimple.infoflow.methodSummary.Main.createSummaries(Main.java:400)
	at soot.jimple.infoflow.methodSummary.Main.runGenerateSummaryWithSpecificClassRoot(Main.java:320)
	at soot.jimple.infoflow.methodSummary.Main.generateSummary(Main.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.OutOfMemoryError: Java heap space

Disconnected from the target VM, address: 'javadebug', transport: 'shared memory'

Process finished with exit code -1
```

**Comment by StevenArzt** [comment]
Try increasing the Java heap size: ``java -Xmx25g -jar ... `` for 25 GB. Try to give the analysis as much memory as you can.

**Comment by LeoYelton** [comment]
> You seem to have inconsistent classes on your target path, probably a result of your merge. The class `org.eclipse.jetty.http.HttpFields` should normally be a class according to [its JavaDoc](https://www.eclipse.org/jetty/javadoc/jetty-10/org/eclipse/jetty/http/HttpField.html). The invocation that Soot processes also refers to a class. For some reason, however, `org.eclipse.jetty.http.HttpFields` is an interface on your target path and not a class. That leads to the error. You should check whether your have incompatible JARs.

Do you means that :
I have two class call the ”HttpFields" ， First one is an interface , second one is a class. When compiling the project "org.eclipse.jetty.http.HttpFields" . It finally get the wrong result in bytecode use interface instead of class. So it get the wrong result. So the error comes from the duplicate name of classes.

**Comment by LeoYelton** [comment]
> Try increasing the Java heap size: `java -Xmx25g -jar ... ` for 25 GB. Try to give the analysis as much memory as you can.

Thank you, I'll try it on a better performance machine.

**Comment by StevenArzt** [comment]
> Do you means that : I have two class call the ”HttpFields" ， First one it an interface , second one is a class. When compiling the project "org.eclipse.jetty.http.HttpFields" . It finally get the wrong result in bytecode use interface instead of class. So it get the wrong result. So it comes from the duplicate name of classes.

This would be the most obvious answer, You can try to debug the ASM class loading in Soot to see where the wrong interface comes from.

**Comment by LeoYelton** [comment]
I use IDEA bytecode util to see the usage of jetty in spring-web
actually it's bytecode is invokespecial but HttpField**s**  is an interface, so it must be invoke virtual instead. Thank for you patient ! Can I ask one more question about another exception? I'm really worried about disturbing you . I'm a student graduate months before.  I'm afraid my question is too simple for professor.
```
 // access flags 0x19
  public final static Lorg/eclipse/jetty/http/HttpFields; EMPTY

  // access flags 0x9
  public static build()Lorg/eclipse/jetty/http/HttpFields$Mutable;
   L0
    LINENUMBER 45 L0
    NEW org/eclipse/jetty/http/HttpFields$Mutable
    DUP
    INVOKESPECIAL org/eclipse/jetty/http/HttpFields$Mutable.<init> ()V
    ARETURN
    MAXSTACK = 2
    MAXLOCALS = 0
```

**Comment by LeoYelton** [comment]
You're so warm-hearted expert , professor . I heard about a speech from TED 2 years ago , said engineer create the world , scientist discover the world. I really hope i can make a such wonderful project like you in the future.

**Comment by StevenArzt** [comment]
> Can I ask one more question about another exception? I'm really worried about disturbing you . I'm a student graduate months before. I'm afraid my question is too simple for professor.

I'll try to answer if I have the time.
