### ISSUE TITLE
How can i solve this problem?

### ISSUE THREAD

**Issue by green-study** [secure-software-engineering/FlowDroid#515]
![image](https://user-images.githubusercontent.com/70996958/189698462-4c567824-72f2-4358-8e07-494c09315e71.png)
[main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Loading dex files...
[main] WARN soot.dexpler.DexFileProvider - Multiple dex files detected, only processing 'classes.dex'. Use '-process-multiple-dex' option to process them all.
The data flow analysis has failed. Error message: None of the basic classes could be loaded! Check your Soot class path!
java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
 at soot.Scene.loadBasicClasses(Scene.java:1723)
        at soot.Scene.loadNecessaryClasses(Scene.java:1804)
        at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1183)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1476)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1451)
        at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:365)
        at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:258)

I want to use flowdroid command line, but error occurs.
How can i solve this problem?

**Comment by green-study** [comment]
I found the cause. 
There was an error in android.jar . 
It just gives a warning and runs fine.

**Comment by StevenArzt** [comment]
For the Android JARs parameter ``-p``, you should specify the ``platforms`` directory of your Android SDK installation, not a single JAR file. Note that you need the SDK with its directory layout, because FlowDroid needs to pick the right JAR.

**Comment by green-study** [comment]
thank you!
