### ISSUE TITLE
Error analysing APK

### ISSUE THREAD

**Issue by turban1988** [secure-software-engineering/FlowDroid#62]
Hi,
I tried to analysze an Androdi malware sample (hash 037c4f5b2cf06c5b18d98c32744621f03e550f2a2ca6485348d188f7b7b5ee99 ) with FlowDorid.

I used the newes FlowDorid version (from the relese packages).

I used the followign command to start the analysis:
`java -jar soot-infoflow-cmd-jar-with-dependencies.jar  -a 037c4f5b2cf06c5b18d98c32744621f03e550f2a2ca6485348d188f7b7b5ee99 -p "H:\Android\Sdk\platforms" -s sas.txt`

Sadly, I get the following error: " Invalid class source type"

```
[main] INFO soot.jimple.infoflow.taintWrappers.EasyTaintWrapper - Loaded wrapper entries for 89 classes and 12 exclusions.
[main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Loading dex files...
Found dex file 'classes.dex' with 5422 classes in 'H:\037c4f5b2cf06c5b18d98c32744621f03e550f2a2ca6485348d188f7b7b5ee99'
The data flow analysis has failed. Error message: Invalid class source type
java.lang.RuntimeException: Invalid class source type
        at soot.SourceLocator.getClassesUnder(SourceLocator.java:378)
        at soot.SourceLocator.getClassesUnder(SourceLocator.java:290)
        at soot.Scene.loadNecessaryClasses(Scene.java:1602)
        at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1121)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1313)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1285)
        at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:236)
        at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:196)
```

**Comment by StevenArzt** [comment]
Can you please provide the APK file? Unfortunately, I don't have that malware sample.

**Comment by StevenArzt** [comment]
Since there has not been any further activity on this thread and since I don't have that malware sample, I close this issue. In case you have a way to provide the sample, please let me know.

**Comment by neupaneprakash** [comment]
Hi @StevenArzt !
I am facing the same issue like this (#62) **:Invalid class source type**
Error Log:
**_```
[main] INFO soot.jimple.infoflow.cmd.MainClass - Analyzing app /home/prakash/Documents/FlowDroid/Apks_List/AdobeAcrobat.apk (1 of 1)...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Loading dex files...
The data flow analysis has failed. Error message: Invalid class source type
java.lang.RuntimeException: Invalid class source type
	at soot.SourceLocator.getClassesUnder(SourceLocator.java:421)
	at soot.SourceLocator.getClassesUnder(SourceLocator.java:317)
	at soot.Scene.loadNecessaryClasses(Scene.java:1819)
	at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1185)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1442)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1417)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:361)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:254)
```_**

I have used following command to run : **java -jar soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar -a ../Apks_List/AdobeAcrobat.apk -p ../Android/Sdk/platforms -s soot-infoflow-android/SourcesAndSinks.txt**

Moreover, I have used latest version of FlowDroid 2.10 and you can get apk file from this link : [(https://www.dropbox.com/s/45pdyue3n1cvi70/AdobeAcrobat.apk?dl=0)]
 I need help to move forward.
