### ISSUE TITLE
Convert Jimple files to dex (The file "parser.dat" is either missing or corrupted)

### ISSUE THREAD

**Issue by Jacoppy** [secure-software-engineering/FlowDroid#68]
Hi,
I'm using FlowDroid for  static analysis on android and I'm trying to parse a Jimple file for getting back a Soot class but I get this : 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Jimple_parser.parse(Jimple_parser.java:23)
	at Instrumenter.main(Instrumenter.java:43)
Caused by: java.lang.RuntimeException: The file "parser.dat" is either missing or corrupted.
	at soot.jimple.parser.parser.Parser.<clinit>(Parser.java:7588)
	... 2 more

This is probably referred to this Soot issue : https://github.com/Sable/soot/issues/726 .
I tried to download the nightybuild but the server seems down.
How can I fix this ?
Thanks

**Comment by Jacoppy** [comment]
Fixed, was my bad, I was on 2.5 FlowDroid
