### ISSUE TITLE
Unable to run flowdroid analysis

### ISSUE THREAD

**Issue by arabin-android** [secure-software-engineering/FlowDroid#74]
Hi I am trying to analyze an apk using flowdroid. however, when i try to run the command in mac i get the following error. can anyone help me with this issue please.

Arabins-MacBook-Pro:FlowDroid-2.6 arabin$ java -jar soot-infoflow-cmd-jar-with-dependencies.jar /Users/arabin/Desktop/1e993b0632d5bc6f07410ee31e41dd316435d997.apk "/Users/arabin/Library/Android/sdk/platforms" /Volumes/E/Flowdroid/FlowDroid-2.6/soot-infoflow-android/SourcesAndSinks.txt
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
The data flow analysis has failed. Error message: Android platform directory not specified
java.lang.RuntimeException: Android platform directory not specified
	at soot.jimple.infoflow.android.SetupApplication.<init>(SetupApplication.java:277)
	at soot.jimple.infoflow.android.SetupApplication.<init>(SetupApplication.java:216)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:230)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:196)

**Comment by zhanghan177** [comment]
```
java -jar soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar \
    -a <APK File> \
    -p <Android JAR folder> \
    -s <SourcesSinks file>
```

Your command doesn't have `-a`, `-p`, `-s` option flags, does it?

**Comment by arabin-android** [comment]
This is the updated command i am using right now. but got the same problem.

Arabins-MacBook-Pro:FlowDroid-2.6 arabin$ java -jar soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar -a /Users/arabin/Desktop/1e993b0632d5bc6f07410ee31e41dd316435d997.apk -p "/Users/arabin/Library/Android/sdk/platforms" -s /Volumes/E/Flowdroid/FlowDroid-2.6/soot-infoflow-android/SourcesAndSinks.txt
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
The data flow analysis has failed. Error message: error in target definition: _BOTH_
java.lang.RuntimeException: error in target definition: _BOTH_
	at soot.jimple.infoflow.android.data.parsers.PermissionMethodParser.parseMethod(PermissionMethodParser.java:237)
	at soot.jimple.infoflow.android.data.parsers.PermissionMethodParser.createMethod(PermissionMethodParser.java:159)
	at soot.jimple.infoflow.android.data.parsers.PermissionMethodParser.parse(PermissionMethodParser.java:135)
	at soot.jimple.infoflow.android.data.parsers.PermissionMethodParser.getSources(PermissionMethodParser.java:110)
	at soot.jimple.infoflow.android.SetupApplication.createSourceSinkManager(SetupApplication.java:524)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:500)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:447)
	at soot.jimple.infoflow.android.SetupApplication.processEntryPoint(SetupApplication.java:1392)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1361)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1307)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:237)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:196)

**Comment by zhanghan177** [comment]
https://github.com/secure-software-engineering/FlowDroid/issues/67? Is it the same issue?

**Comment by StevenArzt** [comment]
Yes, it is the same bug. As I wote in the other issue, you can either remove the corresponding line from the source/sink definition file, or define it either as a source or as a sink instead of both. Or you can clone the "develop" branch and build it on your own (should be pretty easy using maven), because the "develop" branch already contains a fix that adds support for the "BOTH" flag.

**Comment by arabin-android** [comment]
Hello @StevenArzt @zhanghan177 thank you for the valuable time. I have deleted the corresponding line related to "BOTH" from the "SourcesAndSinks.txt" file from "soot-inflow-android" folder. Then initiated the following command and it is not giving any output. rather it is showing the error "Failed to load class "org.slf4j.impl.StaticLoggerBinder".

> -p /Users/arabin/Desktop/1e993b0632d5bc6f07410ee31e41dd316435d997.apk \
>
Arabins-MacBook-Pro:FlowDroid-2.6 arabin$ clear
Arabins-MacBook-Pro:FlowDroid-2.6 arabin$ java -jar soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar \
> -a /Users/arabin/Desktop/1e993b0632d5bc6f07410ee31e41dd316435d997.apk \
> -p /Users/arabin/Library/Android/sdk/platforms \
> -s /Volumes/E/Flowdroid/FlowDroid-2.6/soot-infoflow-android/SourcesAndSinks.txt
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Arabins-MacBook-Pro:FlowDroid-2.6 arabin$

**Comment by StevenArzt** [comment]
It looks like there is no output, because SLF4J does not find a logger to which to write the output. I'm currently working on a fix to include the simple logger implementation in the assembly JAR. A new release is a good idea anyway, because we need to get the fix with the DOUBLE entries officially delivered.

**Comment by arabin-android** [comment]
Thank you @StevenArzt, so can i do the analysis now with the existing flowdroid or i have to wait for the new release?

**Comment by StevenArzt** [comment]
The new release is out now: https://github.com/secure-software-engineering/FlowDroid/releases/tag/v2.6.1. Please try again with the new release.

**Comment by zhanghan177** [comment]
Have you try a different JAR file as
```bash
java -jar soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar \
    -a <APK File> \
    -p <Android JAR folder> \
    -s <SourcesSinks file>
```

**Comment by StevenArzt** [comment]
The output of the analysis is

```
[main] WARN soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - No results found.
```

FlowDroid tell you that there are no connections between any of the sources and sinks you have defined. This can have multiple reasons. The most usual one is that you are missing a source or a sink, and that the app actually doesn't leak the data you are currently looking for.

You can also have FlowDroid write out the results as an XML file using the ```-o``` option, if that is more convenient for you than analyzing the console output. If there are no results, that won't change much, though.

**Comment by arabin-android** [comment]
thank you @zhanghan177 @StevenArzt for the instructions
