### ISSUE TITLE
java.lang.NullPointerException when running the comand line tool

### ISSUE THREAD

**Issue by draftyfrog** [secure-software-engineering/FlowDroid#775]
I ran into an issue with the comand line tool using the newest release [v2.14.1](https://github.com/secure-software-engineering/FlowDroid/tree/v2.14.1).

I run FlowDroid via the command-line tool with

```console
java -jar ./soot-infoflow-cmd-2.14.1-jar-with-dependencies.jar \
 -a {path-to-apk} \
 -s ./SourcesAndSinks.xml \
 -o ./out.xml \
 -p {path-to-android-platforms-folder} \
 --mergedexfiles
```

and my SourcesAndSinks.xml looks like this

```xml
<sinkSources>
    <category id="NO_CATEGORY">
        <method signature="com.example.testapp.MainActivity: java.lang.String source()">
            <return type="java.lang.String">
                <accessPath isSource="true" isSink="false">
                </accessPath>
            </return>
        </method>
        <method signature="com.example.testapp.MainActivity: void sink(java.lang.String)">
            <param index="0" type="java.lang.String">
                <accessPath isSource="false" isSink="true"/>
            </param>
        </method>
    </category>
</sinkSources>
```

After finding some leaks, FlowDroid crashes when trying to write the output file `out.xml`:

```console
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 30 leaks
The data flow analysis has failed. Error message: Cannot invoke "String.length()" because "content" is null
java.lang.NullPointerException: Cannot invoke "String.length()" because "content" is null
        at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeXMLContent(XMLStreamWriterImpl.java:1487)
        at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeAttribute(XMLStreamWriterImpl.java:554)
        at soot.jimple.infoflow.results.xml.InfoflowResultsSerializer.writeSinkInfo(InfoflowResultsSerializer.java:269)
        at soot.jimple.infoflow.results.xml.InfoflowResultsSerializer.writeDataFlows(InfoflowResultsSerializer.java:179)
        at soot.jimple.infoflow.results.xml.InfoflowResultsSerializer.serialize(InfoflowResultsSerializer.java:84)
        at soot.jimple.infoflow.android.SetupApplication.serializeResults(SetupApplication.java:1660)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1547)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1491)
        at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:358)
        at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:256)
```

which then ends up looking like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<DataFlowResults FileFormatVersion="102" TerminationState="Success">
    <Results>
        <Result>
            <Sink Statement="virtualinvoke r0.&lt;com.example.testapp.MainActivity: void sink(java.lang.String)&gt;($r5)"
                  Category="
```

Could this be related to using `<category id="NO_CATEGORY">`? Thanks for any help!

**Comment by StevenArzt** [comment]
Thank you for the bug report. This category has no human-readable name, which may lead to the error you have reported. I have just added a nullness check.

**Comment by draftyfrog** [comment]
Thank you @StevenArzt!

For everybody who might encounter this problem in the future: the correct xml-file also needs to have a description-tag in each category

```xml
<sinkSources>
    <category id="NO_CATEGORY" description="no_category">
        .....
    </category>
</sinkSources>
```
